name: Lumina
version: 1.0.0
main: com.perceus.lumina.Lumina
description: Spellcasting3, rebranded.
authors:
    - Perceus
api-version: '1.20'
load: STARTUP
commands:
    wand:
        description: gives the player a magical wand
        usage: /wand
    givespell:
        description: gives the player a spell item
        usage: /givespell <args>